#开发环境
# 数据源的配置信息
spring:
  datasource:
    url: jdbc:mysql://192.168.0.249:3306/luxury271?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    #连接池的配置信息
  elasticsearch:
    rest:
      uris: 192.168.0.249
      username:
      password:
      connection-timeout: 10000
      read-timeout: 10000


  # Redis配置信息
  redis:
    # Redis数据库索引（默认为0）=0
    #database: 0
    # Redis服务器地址=127.0.0.1
    #host: 127.0.0.1
    #host: 192.168.0.104
    host: 192.168.0.249
    #host: 172.18.1.60
    # Redis服务器连接端口=6379
    port: 6379
    # Redis服务器连接密码（默认为空）=123456
    password: 123456
    # 连接超时时间（毫秒）=1000
    timeout: 5000

  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB

myLog:
  level: debug
  path: D:/luxuryadmin-log

#阿里云OSS配置
#原服务器地址
oss:
  bucketUrl: https://luxuryadmin-test.oss-cn-hangzhou.aliyuncs.com
  #自定义解析后服务器地址
  domain: http://file-test.luxuryadmin.com
  #可以选择其他的地址
  endpoint: https://oss-cn-hangzhou.aliyuncs.com
  #已经在控制台创建的bucket
  bucketName: luxuryadmin-test
  #你上传文件的保存路径，如果bucket中不存在则创建（其实原理并不是文件夹，只是文件名，详情请先阅读官方文档）
  #picLocation: GitClub/image/
  #相应的id和key值，请填写你具体的值，这里不方便展示我自己的。
  accessKeyId: LTAI4FfBXq3pag9SNBRJHtSU
  accessKeySecret: QsfkNiz59wtoyHDFC9Gbq6ZWIJJQxM

#极光推送配置
jiguang:
  masterSecret: 065a3f9bfa4286422ded4d75
  appKey: 2076185b89aab000d4e958aa

kuaker:
  pay:
    wx:
      notifyUrl: http://xre4jq.natappfree.cc/mp/callback/wxPayCallback
      placeUrl: https://api.mch.weixin.qq.com/v3/pay/transactions/jsapi
      loginUrl: https://api.weixin.qq.com/sns/jscode2session
      appid: wxf130eeea7211f811
      secret: 118f6f18f373675c6092444f6ff4a890
      mchid: 1616964232
      certificateSerialNo: 29633827500AA0483BD57C9AD67A1B9B33AAD6E1
      key: E68970C8769B4D27BA56164FF5605737

#集市小程序
baoyang:
  applet:
    appid: wxe4e59d55c310aa0f
    secret: b15a9b0965b40fc2fd1ee7a3ff3ce708
    loginUrl: https://api.weixin.qq.com/sns/jscode2session

es:
  hosts: 1.15.242.181
  port: 9200
  username: elastic
  password: Es123456
  schema: http  # 使用的协议
  connectTimeOut: 1000 #连接超时时间
  socketTimeOut: 30000 #连接超时时间
  connectionRequestTimeOut: 500  #获取连接的超时时间
  maxConnectNum: 100 #最大连接数
  maxConnectPerRoute: 100 #最大路由连接数


