# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 9092
    servlet:
        context-path: /temp

# mysql
spring:
    # 环境 dev|test|pro
    profiles:
        active: dev
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
